#!/bin/bash

function createAirlines() {
  echo "Enrolling the CA admin"
  mkdir -p organizations/peerOrganizations/airlines.airmile.com/

  export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/peerOrganizations/airlines.airmile.com/

  set -x
  fabric-ca-client enroll -u https://admin:adminpw@localhost:7054 --caname ca-airlines --tls.certfiles "${PWD}/organizations/fabric-ca/airlines/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-7054-ca-airlines.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-7054-ca-airlines.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-7054-ca-airlines.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-7054-ca-airlines.pem
    OrganizationalUnitIdentifier: orderer' > "${PWD}/organizations/peerOrganizations/airlines.airmile.com/msp/config.yaml"

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy airlines's CA cert to airlines's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/organizations/peerOrganizations/airlines.airmile.com/msp/tlscacerts"
  cp "${PWD}/organizations/fabric-ca/airlines/ca-cert.pem" "${PWD}/organizations/peerOrganizations/airlines.airmile.com/msp/tlscacerts/ca.crt"

  # Copy airlines's CA cert to airlines's /tlsca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/airlines.airmile.com/tlsca"
  cp "${PWD}/organizations/fabric-ca/airlines/ca-cert.pem" "${PWD}/organizations/peerOrganizations/airlines.airmile.com/tlsca/tlsca.airlines.airmile.com-cert.pem"

  # Copy airlines's CA cert to airlines's /ca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/airlines.airmile.com/ca"
  cp "${PWD}/organizations/fabric-ca/airlines/ca-cert.pem" "${PWD}/organizations/peerOrganizations/airlines.airmile.com/ca/ca.airlines.airmile.com-cert.pem"

  echo "Registering peer0"
  set -x
  fabric-ca-client register --caname ca-airlines --id.name peer0 --id.secret peer0pw --id.type peer --tls.certfiles "${PWD}/organizations/fabric-ca/airlines/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Registering user"
  set -x
  fabric-ca-client register --caname ca-airlines --id.name user1 --id.secret user1pw --id.type client --tls.certfiles "${PWD}/organizations/fabric-ca/airlines/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Registering the org admin"
  set -x
  fabric-ca-client register --caname ca-airlines --id.name airlinesadmin --id.secret airlinesadminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/airlines/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Generating the peer0 msp"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:7054 --caname ca-airlines -M "${PWD}/organizations/peerOrganizations/airlines.airmile.com/peers/peer0.airlines.airmile.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/airlines/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/airlines.airmile.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/airlines.airmile.com/peers/peer0.airlines.airmile.com/msp/config.yaml"

  echo "Generating the peer0-tls certificates, use --csr.hosts to specify Subject Alternative Names"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:7054 --caname ca-airlines -M "${PWD}/organizations/peerOrganizations/airlines.airmile.com/peers/peer0.airlines.airmile.com/tls" --enrollment.profile tls --csr.hosts peer0.airlines.airmile.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/airlines/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the peer's tls directory that are referenced by peer startup config
  cp "${PWD}/organizations/peerOrganizations/airlines.airmile.com/peers/peer0.airlines.airmile.com/tls/tlscacerts/"* "${PWD}/organizations/peerOrganizations/airlines.airmile.com/peers/peer0.airlines.airmile.com/tls/ca.crt"
  cp "${PWD}/organizations/peerOrganizations/airlines.airmile.com/peers/peer0.airlines.airmile.com/tls/signcerts/"* "${PWD}/organizations/peerOrganizations/airlines.airmile.com/peers/peer0.airlines.airmile.com/tls/server.crt"
  cp "${PWD}/organizations/peerOrganizations/airlines.airmile.com/peers/peer0.airlines.airmile.com/tls/keystore/"* "${PWD}/organizations/peerOrganizations/airlines.airmile.com/peers/peer0.airlines.airmile.com/tls/server.key"

  echo "Generating the user msp"
  set -x
  fabric-ca-client enroll -u https://user1:user1pw@localhost:7054 --caname ca-airlines -M "${PWD}/organizations/peerOrganizations/airlines.airmile.com/users/User1@airlines.airmile.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/airlines/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/airlines.airmile.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/airlines.airmile.com/users/User1@airlines.airmile.com/msp/config.yaml"

  echo "Generating the org admin msp"
  set -x
  fabric-ca-client enroll -u https://airlinesadmin:airlinesadminpw@localhost:7054 --caname ca-airlines -M "${PWD}/organizations/peerOrganizations/airlines.airmile.com/users/Admin@airlines.airmile.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/airlines/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/airlines.airmile.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/airlines.airmile.com/users/Admin@airlines.airmile.com/msp/config.yaml"
}

function createMerchants() {
  echo "Enrolling the CA admin"
  mkdir -p organizations/peerOrganizations/merchants.airmile.com/

  export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/peerOrganizations/merchants.airmile.com/

  set -x
  fabric-ca-client enroll -u https://admin:adminpw@localhost:8054 --caname ca-merchants --tls.certfiles "${PWD}/organizations/fabric-ca/merchants/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-8054-ca-merchants.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-8054-ca-merchants.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-8054-ca-merchants.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-8054-ca-merchants.pem
    OrganizationalUnitIdentifier: orderer' > "${PWD}/organizations/peerOrganizations/merchants.airmile.com/msp/config.yaml"

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy merchants's CA cert to merchants's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/organizations/peerOrganizations/merchants.airmile.com/msp/tlscacerts"
  cp "${PWD}/organizations/fabric-ca/merchants/ca-cert.pem" "${PWD}/organizations/peerOrganizations/merchants.airmile.com/msp/tlscacerts/ca.crt"

  # Copy merchants's CA cert to merchants's /tlsca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/merchants.airmile.com/tlsca"
  cp "${PWD}/organizations/fabric-ca/merchants/ca-cert.pem" "${PWD}/organizations/peerOrganizations/merchants.airmile.com/tlsca/tlsca.merchants.airmile.com-cert.pem"

  # Copy merchants's CA cert to merchants's /ca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/merchants.airmile.com/ca"
  cp "${PWD}/organizations/fabric-ca/merchants/ca-cert.pem" "${PWD}/organizations/peerOrganizations/merchants.airmile.com/ca/ca.merchants.airmile.com-cert.pem"

  echo "Registering peer0"
  set -x
  fabric-ca-client register --caname ca-merchants --id.name peer0 --id.secret peer0pw --id.type peer --tls.certfiles "${PWD}/organizations/fabric-ca/merchants/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Registering user"
  set -x
  fabric-ca-client register --caname ca-merchants --id.name user1 --id.secret user1pw --id.type client --tls.certfiles "${PWD}/organizations/fabric-ca/merchants/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Registering the org admin"
  set -x
  fabric-ca-client register --caname ca-merchants --id.name merchantsadmin --id.secret merchantsadminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/merchants/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Generating the peer0 msp"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:8054 --caname ca-merchants -M "${PWD}/organizations/peerOrganizations/merchants.airmile.com/peers/peer0.merchants.airmile.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/merchants/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/merchants.airmile.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/merchants.airmile.com/peers/peer0.merchants.airmile.com/msp/config.yaml"

  echo "Generating the peer0-tls certificates, use --csr.hosts to specify Subject Alternative Names"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:8054 --caname ca-merchants -M "${PWD}/organizations/peerOrganizations/merchants.airmile.com/peers/peer0.merchants.airmile.com/tls" --enrollment.profile tls --csr.hosts peer0.merchants.airmile.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/merchants/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the peer's tls directory that are referenced by peer startup config
  cp "${PWD}/organizations/peerOrganizations/merchants.airmile.com/peers/peer0.merchants.airmile.com/tls/tlscacerts/"* "${PWD}/organizations/peerOrganizations/merchants.airmile.com/peers/peer0.merchants.airmile.com/tls/ca.crt"
  cp "${PWD}/organizations/peerOrganizations/merchants.airmile.com/peers/peer0.merchants.airmile.com/tls/signcerts/"* "${PWD}/organizations/peerOrganizations/merchants.airmile.com/peers/peer0.merchants.airmile.com/tls/server.crt"
  cp "${PWD}/organizations/peerOrganizations/merchants.airmile.com/peers/peer0.merchants.airmile.com/tls/keystore/"* "${PWD}/organizations/peerOrganizations/merchants.airmile.com/peers/peer0.merchants.airmile.com/tls/server.key"

  echo "Generating the user msp"
  set -x
  fabric-ca-client enroll -u https://user1:user1pw@localhost:8054 --caname ca-merchants -M "${PWD}/organizations/peerOrganizations/merchants.airmile.com/users/User1@merchants.airmile.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/merchants/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/merchants.airmile.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/merchants.airmile.com/users/User1@merchants.airmile.com/msp/config.yaml"

  echo "Generating the org admin msp"
  set -x
  fabric-ca-client enroll -u https://merchantsadmin:merchantsadminpw@localhost:8054 --caname ca-merchants -M "${PWD}/organizations/peerOrganizations/merchants.airmile.com/users/Admin@merchants.airmile.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/merchants/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/merchants.airmile.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/merchants.airmile.com/users/Admin@merchants.airmile.com/msp/config.yaml"
}


function createBanks() {
  echo "Enrolling the CA admin"
  mkdir -p organizations/peerOrganizations/banks.airmile.com/

  export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/peerOrganizations/banks.airmile.com/

  set -x
  fabric-ca-client enroll -u https://admin:adminpw@localhost:11054 --caname ca-banks --tls.certfiles "${PWD}/organizations/fabric-ca/banks/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-11054-ca-banks.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-11054-ca-banks.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-11054-ca-banks.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-11054-ca-banks.pem
    OrganizationalUnitIdentifier: orderer' > "${PWD}/organizations/peerOrganizations/banks.airmile.com/msp/config.yaml"

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy banks's CA cert to banks's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/organizations/peerOrganizations/banks.airmile.com/msp/tlscacerts"
  cp "${PWD}/organizations/fabric-ca/banks/ca-cert.pem" "${PWD}/organizations/peerOrganizations/banks.airmile.com/msp/tlscacerts/ca.crt"

  # Copy banks's CA cert to banks's /tlsca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/banks.airmile.com/tlsca"
  cp "${PWD}/organizations/fabric-ca/banks/ca-cert.pem" "${PWD}/organizations/peerOrganizations/banks.airmile.com/tlsca/tlsca.banks.airmile.com-cert.pem"

  # Copy banks's CA cert to banks's /ca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/banks.airmile.com/ca"
  cp "${PWD}/organizations/fabric-ca/banks/ca-cert.pem" "${PWD}/organizations/peerOrganizations/banks.airmile.com/ca/ca.banks.airmile.com-cert.pem"

  echo "Registering peer0"
  set -x
  fabric-ca-client register --caname ca-banks --id.name peer0 --id.secret peer0pw --id.type peer --tls.certfiles "${PWD}/organizations/fabric-ca/banks/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Registering user"
  set -x
  fabric-ca-client register --caname ca-banks --id.name user1 --id.secret user1pw --id.type client --tls.certfiles "${PWD}/organizations/fabric-ca/banks/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Registering the org admin"
  set -x
  fabric-ca-client register --caname ca-banks --id.name banksadmin --id.secret banksadminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/banks/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Generating the peer0 msp"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:11054 --caname ca-banks -M "${PWD}/organizations/peerOrganizations/banks.airmile.com/peers/peer0.banks.airmile.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/banks/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/banks.airmile.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/banks.airmile.com/peers/peer0.banks.airmile.com/msp/config.yaml"

  echo "Generating the peer0-tls certificates, use --csr.hosts to specify Subject Alternative Names"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:11054 --caname ca-banks -M "${PWD}/organizations/peerOrganizations/banks.airmile.com/peers/peer0.banks.airmile.com/tls" --enrollment.profile tls --csr.hosts peer0.banks.airmile.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/banks/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the peer's tls directory that are referenced by peer startup config
  cp "${PWD}/organizations/peerOrganizations/banks.airmile.com/peers/peer0.banks.airmile.com/tls/tlscacerts/"* "${PWD}/organizations/peerOrganizations/banks.airmile.com/peers/peer0.banks.airmile.com/tls/ca.crt"
  cp "${PWD}/organizations/peerOrganizations/banks.airmile.com/peers/peer0.banks.airmile.com/tls/signcerts/"* "${PWD}/organizations/peerOrganizations/banks.airmile.com/peers/peer0.banks.airmile.com/tls/server.crt"
  cp "${PWD}/organizations/peerOrganizations/banks.airmile.com/peers/peer0.banks.airmile.com/tls/keystore/"* "${PWD}/organizations/peerOrganizations/banks.airmile.com/peers/peer0.banks.airmile.com/tls/server.key"

  echo "Generating the user msp"
  set -x
  fabric-ca-client enroll -u https://user1:user1pw@localhost:11054 --caname ca-banks -M "${PWD}/organizations/peerOrganizations/banks.airmile.com/users/User1@banks.airmile.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/banks/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/banks.airmile.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/banks.airmile.com/users/User1@banks.airmile.com/msp/config.yaml"

  echo "Generating the org admin msp"
  set -x
  fabric-ca-client enroll -u https://banksadmin:banksadminpw@localhost:11054 --caname ca-banks -M "${PWD}/organizations/peerOrganizations/banks.airmile.com/users/Admin@banks.airmile.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/banks/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/banks.airmile.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/banks.airmile.com/users/Admin@banks.airmile.com/msp/config.yaml"
}

function createAgency() {
  echo "Enrolling the CA admin"
  mkdir -p organizations/peerOrganizations/agency.airmile.com/

  export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/peerOrganizations/agency.airmile.com/

  set -x
  fabric-ca-client enroll -u https://admin:adminpw@localhost:12054 --caname ca-agency --tls.certfiles "${PWD}/organizations/fabric-ca/agency/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-12054-ca-agency.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-12054-ca-agency.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-12054-ca-agency.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-12054-ca-agency.pem
    OrganizationalUnitIdentifier: orderer' > "${PWD}/organizations/peerOrganizations/agency.airmile.com/msp/config.yaml"

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy agency's CA cert to agency's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/organizations/peerOrganizations/agency.airmile.com/msp/tlscacerts"
  cp "${PWD}/organizations/fabric-ca/agency/ca-cert.pem" "${PWD}/organizations/peerOrganizations/agency.airmile.com/msp/tlscacerts/ca.crt"

  # Copy agency's CA cert to agency's /tlsca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/agency.airmile.com/tlsca"
  cp "${PWD}/organizations/fabric-ca/agency/ca-cert.pem" "${PWD}/organizations/peerOrganizations/agency.airmile.com/tlsca/tlsca.agency.airmile.com-cert.pem"

  # Copy agency's CA cert to agency's /ca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/agency.airmile.com/ca"
  cp "${PWD}/organizations/fabric-ca/agency/ca-cert.pem" "${PWD}/organizations/peerOrganizations/agency.airmile.com/ca/ca.agency.airmile.com-cert.pem"

  echo "Registering peer0"
  set -x
  fabric-ca-client register --caname ca-agency --id.name peer0 --id.secret peer0pw --id.type peer --tls.certfiles "${PWD}/organizations/fabric-ca/agency/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Registering user"
  set -x
  fabric-ca-client register --caname ca-agency --id.name user1 --id.secret user1pw --id.type client --tls.certfiles "${PWD}/organizations/fabric-ca/agency/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Registering the org admin"
  set -x
  fabric-ca-client register --caname ca-agency --id.name agencyadmin --id.secret agencyadminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/agency/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Generating the peer0 msp"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:12054 --caname ca-agency -M "${PWD}/organizations/peerOrganizations/agency.airmile.com/peers/peer0.agency.airmile.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/agency/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/agency.airmile.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/agency.airmile.com/peers/peer0.agency.airmile.com/msp/config.yaml"

  echo "Generating the peer0-tls certificates, use --csr.hosts to specify Subject Alternative Names"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:12054 --caname ca-agency -M "${PWD}/organizations/peerOrganizations/agency.airmile.com/peers/peer0.agency.airmile.com/tls" --enrollment.profile tls --csr.hosts peer0.agency.airmile.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/agency/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the peer's tls directory that are referenced by peer startup config
  cp "${PWD}/organizations/peerOrganizations/agency.airmile.com/peers/peer0.agency.airmile.com/tls/tlscacerts/"* "${PWD}/organizations/peerOrganizations/agency.airmile.com/peers/peer0.agency.airmile.com/tls/ca.crt"
  cp "${PWD}/organizations/peerOrganizations/agency.airmile.com/peers/peer0.agency.airmile.com/tls/signcerts/"* "${PWD}/organizations/peerOrganizations/agency.airmile.com/peers/peer0.agency.airmile.com/tls/server.crt"
  cp "${PWD}/organizations/peerOrganizations/agency.airmile.com/peers/peer0.agency.airmile.com/tls/keystore/"* "${PWD}/organizations/peerOrganizations/agency.airmile.com/peers/peer0.agency.airmile.com/tls/server.key"

  echo "Generating the user msp"
  set -x
  fabric-ca-client enroll -u https://user1:user1pw@localhost:12054 --caname ca-agency -M "${PWD}/organizations/peerOrganizations/agency.airmile.com/users/User1@agency.airmile.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/agency/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/agency.airmile.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/agency.airmile.com/users/User1@agency.airmile.com/msp/config.yaml"

  echo "Generating the org admin msp"
  set -x
  fabric-ca-client enroll -u https://agencyadmin:agencyadminpw@localhost:12054 --caname ca-agency -M "${PWD}/organizations/peerOrganizations/agency.airmile.com/users/Admin@agency.airmile.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/agency/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/agency.airmile.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/agency.airmile.com/users/Admin@agency.airmile.com/msp/config.yaml"
}


function createOrderer() {
  echo "Enrolling the CA admin"
  mkdir -p organizations/ordererOrganizations/airmile.com

  export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/ordererOrganizations/airmile.com

  set -x
  fabric-ca-client enroll -u https://admin:adminpw@localhost:9054 --caname ca-orderer --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-9054-ca-orderer.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-9054-ca-orderer.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-9054-ca-orderer.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-9054-ca-orderer.pem
    OrganizationalUnitIdentifier: orderer' > "${PWD}/organizations/ordererOrganizations/airmile.com/msp/config.yaml"

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy orderer org's CA cert to orderer org's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/organizations/ordererOrganizations/airmile.com/msp/tlscacerts"
  cp "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem" "${PWD}/organizations/ordererOrganizations/airmile.com/msp/tlscacerts/tlsca.airmile.com-cert.pem"

  # Copy orderer org's CA cert to orderer org's /tlsca directory (for use by clients)
  mkdir -p "${PWD}/organizations/ordererOrganizations/airmile.com/tlsca"
  cp "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem" "${PWD}/organizations/ordererOrganizations/airmile.com/tlsca/tlsca.airmile.com-cert.pem"

  echo "Registering orderer"
  set -x
  fabric-ca-client register --caname ca-orderer --id.name orderer --id.secret ordererpw --id.type orderer --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Registering the orderer admin"
  set -x
  fabric-ca-client register --caname ca-orderer --id.name ordererAdmin --id.secret ordererAdminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Generating the orderer msp"
  set -x
  fabric-ca-client enroll -u https://orderer:ordererpw@localhost:9054 --caname ca-orderer -M "${PWD}/organizations/ordererOrganizations/airmile.com/orderers/orderer.airmile.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/ordererOrganizations/airmile.com/msp/config.yaml" "${PWD}/organizations/ordererOrganizations/airmile.com/orderers/orderer.airmile.com/msp/config.yaml"

  echo "Generating the orderer-tls certificates, use --csr.hosts to specify Subject Alternative Names"
  set -x
  fabric-ca-client enroll -u https://orderer:ordererpw@localhost:9054 --caname ca-orderer -M "${PWD}/organizations/ordererOrganizations/airmile.com/orderers/orderer.airmile.com/tls" --enrollment.profile tls --csr.hosts orderer.airmile.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the orderer's tls directory that are referenced by orderer startup config
  cp "${PWD}/organizations/ordererOrganizations/airmile.com/orderers/orderer.airmile.com/tls/tlscacerts/"* "${PWD}/organizations/ordererOrganizations/airmile.com/orderers/orderer.airmile.com/tls/ca.crt"
  cp "${PWD}/organizations/ordererOrganizations/airmile.com/orderers/orderer.airmile.com/tls/signcerts/"* "${PWD}/organizations/ordererOrganizations/airmile.com/orderers/orderer.airmile.com/tls/server.crt"
  cp "${PWD}/organizations/ordererOrganizations/airmile.com/orderers/orderer.airmile.com/tls/keystore/"* "${PWD}/organizations/ordererOrganizations/airmile.com/orderers/orderer.airmile.com/tls/server.key"

  # Copy orderer org's CA cert to orderer's /msp/tlscacerts directory (for use in the orderer MSP definition)
  mkdir -p "${PWD}/organizations/ordererOrganizations/airmile.com/orderers/orderer.airmile.com/msp/tlscacerts"
  cp "${PWD}/organizations/ordererOrganizations/airmile.com/orderers/orderer.airmile.com/tls/tlscacerts/"* "${PWD}/organizations/ordererOrganizations/airmile.com/orderers/orderer.airmile.com/msp/tlscacerts/tlsca.airmile.com-cert.pem"

  echo "Generating the admin msp"
  set -x
  fabric-ca-client enroll -u https://ordererAdmin:ordererAdminpw@localhost:9054 --caname ca-orderer -M "${PWD}/organizations/ordererOrganizations/airmile.com/users/Admin@airmile.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/ordererOrganizations/airmile.com/msp/config.yaml" "${PWD}/organizations/ordererOrganizations/airmile.com/users/Admin@airmile.com/msp/config.yaml"
}

createAirlines
createMerchants
createBanks
createAgency
createOrderer
